//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_CategoriaProducto", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Categoria), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.Producto), true)]
[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_ProductoDetalleVenta", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Producto), "DetalleVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.DetalleVenta), true)]
[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_VentaDetalleVenta", "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Venta), "DetalleVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.DetalleVenta), true)]
[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_EstadoVenta", "Estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Estado), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.Venta), true)]
[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_LocalVenta", "Local", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Local), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.Venta), true)]
[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_UsuarioRol", "Rol", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Rol), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.Usuario), true)]
[assembly: EdmRelationshipAttribute("DBVentaModel", "FK_UsuarioVenta", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EFC2.Usuario), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EFC2.Venta), true)]

#endregion

namespace EFC2
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DBVentaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DBVentaEntities usando la cadena de conexión encontrada en la sección 'DBVentaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public DBVentaEntities() : base("name=DBVentaEntities", "DBVentaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DBVentaEntities.
        /// </summary>
        public DBVentaEntities(string connectionString) : base(connectionString, "DBVentaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DBVentaEntities.
        /// </summary>
        public DBVentaEntities(EntityConnection connection) : base(connection, "DBVentaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Categoria> Categoria
        {
            get
            {
                if ((_Categoria == null))
                {
                    _Categoria = base.CreateObjectSet<Categoria>("Categoria");
                }
                return _Categoria;
            }
        }
        private ObjectSet<Categoria> _Categoria;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleVenta> DetalleVenta
        {
            get
            {
                if ((_DetalleVenta == null))
                {
                    _DetalleVenta = base.CreateObjectSet<DetalleVenta>("DetalleVenta");
                }
                return _DetalleVenta;
            }
        }
        private ObjectSet<DetalleVenta> _DetalleVenta;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Estado> Estado
        {
            get
            {
                if ((_Estado == null))
                {
                    _Estado = base.CreateObjectSet<Estado>("Estado");
                }
                return _Estado;
            }
        }
        private ObjectSet<Estado> _Estado;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Local> Local
        {
            get
            {
                if ((_Local == null))
                {
                    _Local = base.CreateObjectSet<Local>("Local");
                }
                return _Local;
            }
        }
        private ObjectSet<Local> _Local;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> Producto
        {
            get
            {
                if ((_Producto == null))
                {
                    _Producto = base.CreateObjectSet<Producto>("Producto");
                }
                return _Producto;
            }
        }
        private ObjectSet<Producto> _Producto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Rol> Rol
        {
            get
            {
                if ((_Rol == null))
                {
                    _Rol = base.CreateObjectSet<Rol>("Rol");
                }
                return _Rol;
            }
        }
        private ObjectSet<Rol> _Rol;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Venta> Venta
        {
            get
            {
                if ((_Venta == null))
                {
                    _Venta = base.CreateObjectSet<Venta>("Venta");
                }
                return _Venta;
            }
        }
        private ObjectSet<Venta> _Venta;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Categoria. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCategoria(Categoria categoria)
        {
            base.AddObject("Categoria", categoria);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleVenta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleVenta(DetalleVenta detalleVenta)
        {
            base.AddObject("DetalleVenta", detalleVenta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Estado. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEstado(Estado estado)
        {
            base.AddObject("Estado", estado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Local. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLocal(Local local)
        {
            base.AddObject("Local", local);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProducto(Producto producto)
        {
            base.AddObject("Producto", producto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Rol. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRol(Rol rol)
        {
            base.AddObject("Rol", rol);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Venta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVenta(Venta venta)
        {
            base.AddObject("Venta", venta);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Categoria.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tipoCategoria">Valor inicial de la propiedad tipoCategoria.</param>
        public static Categoria CreateCategoria(global::System.Int32 id, global::System.String tipoCategoria)
        {
            Categoria categoria = new Categoria();
            categoria.id = id;
            categoria.tipoCategoria = tipoCategoria;
            return categoria;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipoCategoria
        {
            get
            {
                return _tipoCategoria;
            }
            set
            {
                OntipoCategoriaChanging(value);
                ReportPropertyChanging("tipoCategoria");
                _tipoCategoria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipoCategoria");
                OntipoCategoriaChanged();
            }
        }
        private global::System.String _tipoCategoria;
        partial void OntipoCategoriaChanging(global::System.String value);
        partial void OntipoCategoriaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_CategoriaProducto", "Producto")]
        public EntityCollection<Producto> Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Producto>("DBVentaModel.FK_CategoriaProducto", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Producto>("DBVentaModel.FK_CategoriaProducto", "Producto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="DetalleVenta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleVenta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleVenta.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="total">Valor inicial de la propiedad total.</param>
        /// <param name="venta_id">Valor inicial de la propiedad Venta_id.</param>
        /// <param name="producto_id">Valor inicial de la propiedad Producto_id.</param>
        public static DetalleVenta CreateDetalleVenta(global::System.Int32 id, global::System.Int32 total, global::System.Int32 venta_id, global::System.Int32 producto_id)
        {
            DetalleVenta detalleVenta = new DetalleVenta();
            detalleVenta.id = id;
            detalleVenta.total = total;
            detalleVenta.Venta_id = venta_id;
            detalleVenta.Producto_id = producto_id;
            return detalleVenta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private global::System.Int32 _total;
        partial void OntotalChanging(global::System.Int32 value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Venta_id
        {
            get
            {
                return _Venta_id;
            }
            set
            {
                OnVenta_idChanging(value);
                ReportPropertyChanging("Venta_id");
                _Venta_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Venta_id");
                OnVenta_idChanged();
            }
        }
        private global::System.Int32 _Venta_id;
        partial void OnVenta_idChanging(global::System.Int32 value);
        partial void OnVenta_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Producto_id
        {
            get
            {
                return _Producto_id;
            }
            set
            {
                OnProducto_idChanging(value);
                ReportPropertyChanging("Producto_id");
                _Producto_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Producto_id");
                OnProducto_idChanged();
            }
        }
        private global::System.Int32 _Producto_id;
        partial void OnProducto_idChanging(global::System.Int32 value);
        partial void OnProducto_idChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_ProductoDetalleVenta", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("DBVentaModel.FK_ProductoDetalleVenta", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("DBVentaModel.FK_ProductoDetalleVenta", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("DBVentaModel.FK_ProductoDetalleVenta", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("DBVentaModel.FK_ProductoDetalleVenta", "Producto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_VentaDetalleVenta", "Venta")]
        public Venta Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("DBVentaModel.FK_VentaDetalleVenta", "Venta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("DBVentaModel.FK_VentaDetalleVenta", "Venta").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venta> VentaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("DBVentaModel.FK_VentaDetalleVenta", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venta>("DBVentaModel.FK_VentaDetalleVenta", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Estado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Estado.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tipoEstado">Valor inicial de la propiedad tipoEstado.</param>
        public static Estado CreateEstado(global::System.Int32 id, global::System.String tipoEstado)
        {
            Estado estado = new Estado();
            estado.id = id;
            estado.tipoEstado = tipoEstado;
            return estado;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipoEstado
        {
            get
            {
                return _tipoEstado;
            }
            set
            {
                OntipoEstadoChanging(value);
                ReportPropertyChanging("tipoEstado");
                _tipoEstado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipoEstado");
                OntipoEstadoChanged();
            }
        }
        private global::System.String _tipoEstado;
        partial void OntipoEstadoChanging(global::System.String value);
        partial void OntipoEstadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_EstadoVenta", "Venta")]
        public EntityCollection<Venta> Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("DBVentaModel.FK_EstadoVenta", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("DBVentaModel.FK_EstadoVenta", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Local")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Local : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Local.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        public static Local CreateLocal(global::System.Int32 id, global::System.String nombre, global::System.String direccion)
        {
            Local local = new Local();
            local.id = id;
            local.nombre = nombre;
            local.direccion = direccion;
            return local;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_LocalVenta", "Venta")]
        public EntityCollection<Venta> Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("DBVentaModel.FK_LocalVenta", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("DBVentaModel.FK_LocalVenta", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="stock">Valor inicial de la propiedad stock.</param>
        /// <param name="detalle">Valor inicial de la propiedad detalle.</param>
        /// <param name="categoria_id">Valor inicial de la propiedad Categoria_id.</param>
        /// <param name="cod_producto">Valor inicial de la propiedad cod_producto.</param>
        public static Producto CreateProducto(global::System.Int32 id, global::System.String nombre, global::System.Int32 precio, global::System.Int32 stock, global::System.String detalle, global::System.Int32 categoria_id, global::System.String cod_producto)
        {
            Producto producto = new Producto();
            producto.id = id;
            producto.nombre = nombre;
            producto.precio = precio;
            producto.stock = stock;
            producto.detalle = detalle;
            producto.Categoria_id = categoria_id;
            producto.cod_producto = cod_producto;
            return producto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Int32 _precio;
        partial void OnprecioChanging(global::System.Int32 value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stock
        {
            get
            {
                return _stock;
            }
            set
            {
                OnstockChanging(value);
                ReportPropertyChanging("stock");
                _stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stock");
                OnstockChanged();
            }
        }
        private global::System.Int32 _stock;
        partial void OnstockChanging(global::System.Int32 value);
        partial void OnstockChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String detalle
        {
            get
            {
                return _detalle;
            }
            set
            {
                OndetalleChanging(value);
                ReportPropertyChanging("detalle");
                _detalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("detalle");
                OndetalleChanged();
            }
        }
        private global::System.String _detalle;
        partial void OndetalleChanging(global::System.String value);
        partial void OndetalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categoria_id
        {
            get
            {
                return _Categoria_id;
            }
            set
            {
                OnCategoria_idChanging(value);
                ReportPropertyChanging("Categoria_id");
                _Categoria_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Categoria_id");
                OnCategoria_idChanged();
            }
        }
        private global::System.Int32 _Categoria_id;
        partial void OnCategoria_idChanging(global::System.Int32 value);
        partial void OnCategoria_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cod_producto
        {
            get
            {
                return _cod_producto;
            }
            set
            {
                Oncod_productoChanging(value);
                ReportPropertyChanging("cod_producto");
                _cod_producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cod_producto");
                Oncod_productoChanged();
            }
        }
        private global::System.String _cod_producto;
        partial void Oncod_productoChanging(global::System.String value);
        partial void Oncod_productoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_CategoriaProducto", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("DBVentaModel.FK_CategoriaProducto", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("DBVentaModel.FK_CategoriaProducto", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("DBVentaModel.FK_CategoriaProducto", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("DBVentaModel.FK_CategoriaProducto", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_ProductoDetalleVenta", "DetalleVenta")]
        public EntityCollection<DetalleVenta> DetalleVenta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleVenta>("DBVentaModel.FK_ProductoDetalleVenta", "DetalleVenta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleVenta>("DBVentaModel.FK_ProductoDetalleVenta", "DetalleVenta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Rol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rol : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Rol.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tipoRol">Valor inicial de la propiedad tipoRol.</param>
        public static Rol CreateRol(global::System.Int32 id, global::System.String tipoRol)
        {
            Rol rol = new Rol();
            rol.id = id;
            rol.tipoRol = tipoRol;
            return rol;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipoRol
        {
            get
            {
                return _tipoRol;
            }
            set
            {
                OntipoRolChanging(value);
                ReportPropertyChanging("tipoRol");
                _tipoRol = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipoRol");
                OntipoRolChanged();
            }
        }
        private global::System.String _tipoRol;
        partial void OntipoRolChanging(global::System.String value);
        partial void OntipoRolChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_UsuarioRol", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("DBVentaModel.FK_UsuarioRol", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("DBVentaModel.FK_UsuarioRol", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombreusuario">Valor inicial de la propiedad nombreusuario.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="rol_id">Valor inicial de la propiedad Rol_id.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nombreusuario, global::System.String password, global::System.Int32 rol_id)
        {
            Usuario usuario = new Usuario();
            usuario.id = id;
            usuario.nombreusuario = nombreusuario;
            usuario.password = password;
            usuario.Rol_id = rol_id;
            return usuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreusuario
        {
            get
            {
                return _nombreusuario;
            }
            set
            {
                OnnombreusuarioChanging(value);
                ReportPropertyChanging("nombreusuario");
                _nombreusuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreusuario");
                OnnombreusuarioChanged();
            }
        }
        private global::System.String _nombreusuario;
        partial void OnnombreusuarioChanging(global::System.String value);
        partial void OnnombreusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rol_id
        {
            get
            {
                return _Rol_id;
            }
            set
            {
                OnRol_idChanging(value);
                ReportPropertyChanging("Rol_id");
                _Rol_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rol_id");
                OnRol_idChanged();
            }
        }
        private global::System.Int32 _Rol_id;
        partial void OnRol_idChanging(global::System.Int32 value);
        partial void OnRol_idChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_UsuarioRol", "Rol")]
        public Rol Rol
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rol>("DBVentaModel.FK_UsuarioRol", "Rol").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rol>("DBVentaModel.FK_UsuarioRol", "Rol").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rol> RolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rol>("DBVentaModel.FK_UsuarioRol", "Rol");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rol>("DBVentaModel.FK_UsuarioRol", "Rol", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_UsuarioVenta", "Venta")]
        public EntityCollection<Venta> Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("DBVentaModel.FK_UsuarioVenta", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("DBVentaModel.FK_UsuarioVenta", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBVentaModel", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Venta.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="usuario_id">Valor inicial de la propiedad Usuario_id.</param>
        /// <param name="local_id">Valor inicial de la propiedad Local_id.</param>
        /// <param name="estado_id">Valor inicial de la propiedad Estado_id.</param>
        /// <param name="codVenta">Valor inicial de la propiedad codVenta.</param>
        public static Venta CreateVenta(global::System.Int32 id, global::System.DateTime fecha, global::System.Int32 usuario_id, global::System.Int32 local_id, global::System.Int32 estado_id, global::System.String codVenta)
        {
            Venta venta = new Venta();
            venta.id = id;
            venta.fecha = fecha;
            venta.Usuario_id = usuario_id;
            venta.Local_id = local_id;
            venta.Estado_id = estado_id;
            venta.codVenta = codVenta;
            return venta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Usuario_id
        {
            get
            {
                return _Usuario_id;
            }
            set
            {
                OnUsuario_idChanging(value);
                ReportPropertyChanging("Usuario_id");
                _Usuario_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Usuario_id");
                OnUsuario_idChanged();
            }
        }
        private global::System.Int32 _Usuario_id;
        partial void OnUsuario_idChanging(global::System.Int32 value);
        partial void OnUsuario_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Local_id
        {
            get
            {
                return _Local_id;
            }
            set
            {
                OnLocal_idChanging(value);
                ReportPropertyChanging("Local_id");
                _Local_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Local_id");
                OnLocal_idChanged();
            }
        }
        private global::System.Int32 _Local_id;
        partial void OnLocal_idChanging(global::System.Int32 value);
        partial void OnLocal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estado_id
        {
            get
            {
                return _Estado_id;
            }
            set
            {
                OnEstado_idChanging(value);
                ReportPropertyChanging("Estado_id");
                _Estado_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estado_id");
                OnEstado_idChanged();
            }
        }
        private global::System.Int32 _Estado_id;
        partial void OnEstado_idChanging(global::System.Int32 value);
        partial void OnEstado_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codVenta
        {
            get
            {
                return _codVenta;
            }
            set
            {
                OncodVentaChanging(value);
                ReportPropertyChanging("codVenta");
                _codVenta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codVenta");
                OncodVentaChanged();
            }
        }
        private global::System.String _codVenta;
        partial void OncodVentaChanging(global::System.String value);
        partial void OncodVentaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_VentaDetalleVenta", "DetalleVenta")]
        public EntityCollection<DetalleVenta> DetalleVenta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleVenta>("DBVentaModel.FK_VentaDetalleVenta", "DetalleVenta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleVenta>("DBVentaModel.FK_VentaDetalleVenta", "DetalleVenta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_EstadoVenta", "Estado")]
        public Estado Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("DBVentaModel.FK_EstadoVenta", "Estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("DBVentaModel.FK_EstadoVenta", "Estado").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estado> EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("DBVentaModel.FK_EstadoVenta", "Estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estado>("DBVentaModel.FK_EstadoVenta", "Estado", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_LocalVenta", "Local")]
        public Local Local
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Local>("DBVentaModel.FK_LocalVenta", "Local").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Local>("DBVentaModel.FK_LocalVenta", "Local").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Local> LocalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Local>("DBVentaModel.FK_LocalVenta", "Local");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Local>("DBVentaModel.FK_LocalVenta", "Local", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBVentaModel", "FK_UsuarioVenta", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DBVentaModel.FK_UsuarioVenta", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DBVentaModel.FK_UsuarioVenta", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DBVentaModel.FK_UsuarioVenta", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("DBVentaModel.FK_UsuarioVenta", "Usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
